TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += keylkg.db
DATA += keylkg.proto

#=======================================
include $(TOP)/configure/RULES
